### ISSUE TITLE
Przeszukiwanie danych w KRS nie działa w wersji API v3

### ISSUE THREAD

**Issue by jakublipinski** [epforgpl/_mojePanstwo-API-Server#53]
Wyszukiwanie https://api-v3.mojepanstwo.pl/dane/krs_podmioty?q=maspex zwraca dużo (wszystkie?) rekordy
Podobne wyszukiwanie w API v1 działa poprawnie: https://api.mojepanstwo.pl/krs/podmioty?q=maspex

Jak wyszukiwać w API v3?

**Comment by KrzysztofMadejski** [comment]
Trzeba stosować formę https://api-v3.mojepanstwo.pl/dane/krs_podmioty?conditions[q]=maspex
