### ISSUE TITLE
Szwankujące działanie api. 

### ISSUE THREAD

**Issue by vindemi** [epforgpl/_mojePanstwo-API-Server#56]
Witam serdecznie,

piszę z zapytaniem czy Wasze api udostępnia w prosty sposób dane finansowania dla danej gminy (np. https://mojepanstwo.pl/dane/gminy/2023,suwalki/finanse). Chodzi mi o to, czy mogę w łatwy sposób dostać się do odpowiednich wydatków na poszczególne sekcje/sektory poprzez Wasze API? Np. wyciągnąć dane dla gminy suwałki z sekcji "Oświata i wychowanie" a następnie szczegółowe wydatki w tym dziale. (Niestety bank danych lokalnych również źle działa, nawet wasze przykłady na stronie https://mojepanstwo.pl/api/bdl, np. https://api-v3.mojepanstwo.pl/bdl/series?metric_id=762&slice=5479,1713&powiat_id=2)

Obecnie mam problem z dostaniem się do danych. Np. też ciężko jest jakkolwiek przefiltrować gminy na podstawie nazwy lub liczby ludności przy wykorzystaniu api-v3.mojepanstwo.pl

Np takie zapytanie działa:

https://api-v3.mojepanstwo.pl/dane/gminy?layers[]=data?conditions[gminy.id]=1345

ale tylko takie, reszta (zwłaszcza wyszukania zakresowe) nie działają w ogóle lub nie tak jak powinny.
np.

https://api-v3.mojepanstwo.pl/dane/gminy?layers[]=dataset?conditions[gminy.typ_id=3]=3

zwraca różne gminy, a nie tylko te, które mają typ 3.

Będę niezmiernie wdzięczny za odpowiedź.

**Comment by vindemi** [comment]
Ktoś mógłby wypowiedzieć się jakkolwiek na ten temat? Bo trochę jestem w rozkroku, gdzie muszę niedługo podać temat pracy magisterskiej a nie wiem czy mam ryzykować i oprzeć się na tym obecnie, nie działającym API? 
Proszę.

**Comment by danielmacyszyn** [comment]
Jeśli chodzi o ostatni request, to powinien on wyglądać tak:
https://api-v3.mojepanstwo.pl/dane/gminy?conditions[gminy.typ_id]=3

Mechanizm warstw (layers) działa tylko przy odpytywaniu konkretnej gminy, np:
https://api-v3.mojepanstwo.pl/dane/gminy/1.json?layers[]=szef

Do końca tygodniu na stronie https://mojepanstwo.pl/api dodamy rozdziały opisujące pobieranie danych finansowych i BDL

**Comment by vindemi** [comment]
Świetna wiadomość! Dziękuję za odpowiedź. Super także, że opisy/tutoriale dot. api będą lepiej opisane i wyjaśnione.

**Comment by danielmacyszyn** [comment]
Witam
Dzisiaj pod wspomnianym adresme pojawią się wszlekie opisy.
Pozdrawiam

**Comment by danielmacyszyn** [comment]
Do requestu umożliwiającego pobieranie informacji o gminach:
https://api-v3-test.mojepanstwo.pl/dane/gminy.json
dodaliśmy obsługę parametru `fields`, który umożliwia pobieranie informacji o finansach gmin.

Dostępne jest 6 wartości tego parametru:
- `gminy-wydatki-okresy`
- `gminy-wydatki-dzialy`
- `gminy-wydatki-rozdzialy`
- `gminy-dochody-okresy`
- `gminy-dochody-dzialy`
- `gminy-dochody-rozdzialy`

Np:
https://api-v3-test.mojepanstwo.pl/dane/gminy.json?fields[]=gminy-wydatki-okresy

Wtedy w wynikach, oprócz podstawowych informacji o gminach, dostaniemy również parametry o danych finansowych, o których Pan wspominał.

Właśnie kończymy opis tych requestów i danych na stronie https://mojepanstwo.pl/api
Powinien się pojawić dzisiaj.

Pozdrawiam

**Comment by vindemi** [comment]
Czy opisy requestów są już gdzieś wstawione (może pod innym adresem?), bo niestety na stronach:
https://mojepanstwo.pl/api
https://mojepanstwo.pl/api/bdl

Opisy są nadal nieaktualne, a przykłady nie działają i zwracają błąd.

**Comment by vindemi** [comment]
Niestety linki w opisie api nadal nie działają.
https://mojepanstwo.pl/api/bdl

Szkoda, że opisy są takie skrótowe i lakoniczne. Przydałby się dobry, prosty tutorial plus działające przykłady.

**Comment by vindemi** [comment]
Witam, 
niestety fields - **gminy-wydatki-dzialy** oraz **gminy-wydatki-rozdzialy** przestały działać. 
https://api-v3-test.mojepanstwo.pl/dane/gminy?conditions[powiaty.nazwa]=kłodzki&fields[]=gminy-wydatki-dzialy
https://api-v3-test.mojepanstwo.pl/dane/gminy?conditions[powiaty.nazwa]=kłodzki&fields[]=gminy-wydatki-rozdzialy

**ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.**

Dla innych pól zapytanie zwraca poprawne dane

Pozdrawiam

**Comment by vindemi** [comment]
Witam ponownie. Po ostatnim problemie z serwerami hostującymi aplikację, przy wywołaniu requestu:
https://api-v3-test.mojepanstwo.pl/dane/gminy.json
otrzymujemy na samym początku komunikat o błędzie:

> Warning (2): file_put_contents(): Only 0 of 98520 bytes written, possibly out of free disk space [CORE/Cake/Log/Engine/FileLog.php, line 148]

Przez ten błąd nie można odpowiednio zdeserializować danych.

Pozdrawiam.

**Comment by vindemi** [comment]
@danielmacyszyn
Witam ponownie.
Po ostatnim problemie z serwerami hostującymi aplikację, przy wywołaniu requestu:
https://api-v3-test.mojepanstwo.pl/dane/gminy.json (również z wykorzystaniem pól fields)
otrzymujemy na samym początku komunikat o błędzie:

> Warning (2): file_put_contents(): Only 0 of 98520 bytes written, possibly out of free disk space [CORE/Cake/Log/Engine/FileLog.php, line 148]

Przez ten błąd nie można odpowiednio zdeserializować danych, a są mi one potrzebne do pracy magisterskiej.

Pozdrawiam.

**Comment by danielmacyszyn** [comment]
Proszę spróbować teraz
PS. oraz używać hosta api-v3.mojepanstwo.pl

**Comment by vindemi** [comment]
@danielmacyszyn 
Niestety ponownie api szwankuje. Tym razem nie działają wspomniane wyżej parametry:

- gminy-wydatki-okresy
- gminy-wydatki-dzialy
- gminy-wydatki-rozdzialy
- gminy-dochody-okresy
- gminy-dochody-dzialy
- gminy-dochody-rozdzialy

Nie ważne, którego użyję wszystkie zapytania zwracają to samo - bez żadnych wastw. A w tym momencie są one mi ogromnie potrzebne ponieważ zostały użyte w mojej pracy magisterskiej. Prosiłbym o szybkie wsparcie.

Również na głównej stronie mojepanstwo.pl (https://mojepanstwo.pl/dane/gminy/471,gdansk/finanse)
Nie działa w ogóle zakładka finansów w której to prawdopodobnie również parametry te zostały użyte.

Pozdrawiam.
