### ISSUE TITLE
Nie działa wyszukiwanie po nazwie gminy.

### ISSUE THREAD

**Issue by vindemi** [epforgpl/_mojePanstwo-API-Server#67]
Zauważyłem problem z przeszukiwaniem gmin po nazwie.

Mianowicie, to co jest w opisie API nie jest prawdą (lub po prostu obecnie nie działa):

> conditions - Filtry ograniczające zbiór danych, można filtrować po wszystkich polach zwracanych w tablicy data wybranego obiektu, np. ?conditions[imie]=Jan&conditions[nazwisko]=Kowalski 

Jednak takie zapytanie nic nie zwraca: https://api-v3.mojepanstwo.pl/dane/gminy?conditions[gminy.nazwa]=Wąbrzeźno

Wchodząc zaś z poziomu wyszukiwarki na mojepanstwo.pl taka funkcjonalność działa, tylko zastanawiam się jakie zapytanie za tym stoi?
https://mojepanstwo.pl/kto_tu_rzadzi/gminy?q=W%C4%85brze%C5%BAno

Także mam zagwozdkę dotyczącą limitu pobieranych danych. Chciałem ściągnąć wszystkie gminy na raz jednak wychodzi na to, że odgórny limit to 500 rekordów per zapytanie. Czy da się to jakoś obejść?

Pozdrawiam.

**Comment by danielmacyszyn** [comment]
Poprawiliśmy to. Można już użyć linku:
https://api-v3.mojepanstwo.pl/dane/gminy?conditions[gminy.nazwa]=Wąbrzeźno

Aby pobrać informacje o wszystkich gminach należy użyć mechanizmy stronnicowania (parametr `page`)
