### ISSUE TITLE
Zapytania zwraca jeden powiat, a powinno wszystkie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-API-Server#7]
niestety poniższe zapytanie cały czas zwraca tylko jedno powiat_id (powinno zwrócić wszystkie powiaty, prawda?) 
http://api.mojepanstwo.pl/bdl/series?metric_id=139&time_range=1998%3A1998&powiat_id=*

**Comment by pkol** [comment]
Raz dwa trzy, próba mikrofonu. Są jakieś szanse na naprawę?

**Comment by KrzysztofMadejski** [comment]
Jest jeszcze jeden problem z zapytaniami dot. powiatów (poza tym od @Pawel_Kolodziej) . Zauważyłem, że zapytania tego typu: http://api.mojepanstwo.pl/bdl/series?metric_id=763&time_range=2013%3A2013&powiat_id=* zwracają 379 rekordów (a powinno być ich 380).

W kilku przypadkach porównałem dane z API z identycznymi w BDLu i wychodzi na to, że brakującym powiatem jest powiat m.Wałbrzych. To może wynikać ze zmian statusu miasta: http://pl.wikipedia.org/wiki/Miasto_na_prawach_powiatu#Historia

**Comment by KrzysztofMadejski** [comment]
Działam..
